// Copyright (c) 2025 Traian Avram. All rights reserved.
// This source file is part of the PvZ-Remake project and is distributed under the MIT license.

#pragma once

#define PLANT_SUNFLOWER_SUN_COST                            (50)
#define PLANT_SUNFLOWER_PLANT_COOLDOWN_DELAY                (5.0F)
#define PLANT_SUNFLOWER_HEALTH                              (300.0F)
#define PLANT_SUNFLOWER_GENERATE_SUN_DELAY_BASE             (24.0F)
#define PLANT_SUNFLOWER_GENERATE_SUN_DELAY_RANDOM_OFFSET    (0.5F)
#define PLANT_SUNFLOWER_SUN_AMOUNT                          (25)
#define PLANT_SUNFLOWER_SUN_RADIUS                          (0.35F)
#define PLANT_SUNFLOWER_SUN_DECAY                           (8.5F)
#define PLANT_SUNFLOWER_DIMENSIONS_X                        (0.7F)
#define PLANT_SUNFLOWER_DIMENSIONS_Y                        (0.7F)
#define PLANT_SUNFLOWER_RENDER_SCALE_X                      (1.0F)
#define PLANT_SUNFLOWER_RENDER_SCALE_Y                      (1.0F)
#define PLANT_SUNFLOWER_RENDER_OFFSET_X                     (0.0F)
#define PLANT_SUNFLOWER_RENDER_OFFSET_Y                     (0.0F)

#define PLANT_PEASHOOTER_SUN_COST                           (100)
#define PLANT_PEASHOOTER_PLANT_COOLDOWN_DELAY               (5.0F)
#define PLANT_PEASHOOTER_HEALTH                             (300.0F)
#define PLANT_PEASHOOTER_DIMENSIONS_X                       (0.7F)
#define PLANT_PEASHOOTER_DIMENSIONS_Y                       (0.7F)
#define PLANT_PEASHOOTER_RENDER_SCALE_X                     (1.0F)
#define PLANT_PEASHOOTER_RENDER_SCALE_Y                     (1.0F)
#define PLANT_PEASHOOTER_RENDER_OFFSET_X                    (0.0F)
#define PLANT_PEASHOOTER_RENDER_OFFSET_Y                    (0.0F)
#define PLANT_PEASHOOTER_SHOOT_DELAY                        (1.425F)
#define PLANT_PEASHOOTER_PROJECTILE_RADIUS                  (0.1F)
#define PLANT_PEASHOOTER_PROJECTILE_DAMAGE                  (20.0F)
#define PLANT_PEASHOOTER_PROJECTILE_VELOCITY                (5.0F)
#define PLANT_PEASHOOTER_SHOOT_POINT_OFFSET_X               (0.25F)
#define PLANT_PEASHOOTER_SHOOT_POINT_OFFSET_Y               (0.2F)

#define PLANT_REPEATER_SUN_COST                             (200)
#define PLANT_REPEATER_PLANT_COOLDOWN_DELAY                 (5.0F)
#define PLANT_REPEATER_HEALTH                               (300.0F)
#define PLANT_REPEATER_DIMENSIONS_X                         (PLANT_PEASHOOTER_DIMENSIONS_X)
#define PLANT_REPEATER_DIMENSIONS_Y                         (PLANT_PEASHOOTER_DIMENSIONS_Y)
#define PLANT_REPEATER_RENDER_SCALE_X                       (PLANT_PEASHOOTER_RENDER_SCALE_X)
#define PLANT_REPEATER_RENDER_SCALE_Y                       (PLANT_PEASHOOTER_RENDER_SCALE_Y)
#define PLANT_REPEATER_RENDER_OFFSET_X                      (PLANT_PEASHOOTER_RENDER_OFFSET_X)
#define PLANT_REPEATER_RENDER_OFFSET_Y                      (PLANT_PEASHOOTER_RENDER_OFFSET_Y)
#define PLANT_REPEATER_SHOOT_SEQUENCE_DELTA_DELAY           (0.15F)
#define PLANT_REPEATER_SHOOT_SEQUENCE_DELAY                 (PLANT_PEASHOOTER_SHOOT_DELAY - PLANT_REPEATER_SHOOT_SEQUENCE_DELTA_DELAY)
#define PLANT_REPEATER_PROJECTILE_DAMAGE                    (PLANT_PEASHOOTER_PROJECTILE_DAMAGE)
#define PLANT_REPEATER_PROJECTILE_VELOCITY                  (PLANT_PEASHOOTER_PROJECTILE_VELOCITY)
#define PLANT_REPEATER_PROJECTILE_RADIUS                    (PLANT_PEASHOOTER_PROJECTILE_RADIUS)
#define PLANT_REPEATER_SHOOT_POINT_OFFSET_X                 (PLANT_PEASHOOTER_SHOOT_POINT_OFFSET_X)
#define PLANT_REPEATER_SHOOT_POINT_OFFSET_Y                 (PLANT_PEASHOOTER_SHOOT_POINT_OFFSET_Y)

#define PLANT_TORCHWOOD_SUN_COST                            (175)
#define PLANT_TORCHWOOD_PLANT_COOLDOWN_DELAY                (3.0F)
#define PLANT_TORCHWOOD_HEALTH                              (200.0F)
#define PLANT_TORCHWOOD_DIMENSIONS_X                        (0.7F)
#define PLANT_TORCHWOOD_DIMENSIONS_Y                        (0.7F)
#define PLANT_TORCHWOOD_RENDER_SCALE_X                      (1.0F)
#define PLANT_TORCHWOOD_RENDER_SCALE_Y                      (1.0F)
#define PLANT_TORCHWOOD_RENDER_OFFSET_X                     (0.0F)
#define PLANT_TORCHWOOD_RENDER_OFFSET_Y                     (0.0F)
#define PLANT_TORCHWOOD_DAMAGE_MULTIPLIER                   (2.0F)

#define ZOMBIE_NORMAL_HEALTH                                (200.0F)
#define ZOMBIE_NORMAL_DIMENSIONS_X                          (0.8F)
#define ZOMBIE_NORMAL_DIMENSIONS_Y                          (1.28F)
#define ZOMBIE_NORMAL_RENDER_SCALE_X                        (1.0F)
#define ZOMBIE_NORMAL_RENDER_SCALE_Y                        (1.0F)
#define ZOMBIE_NORMAL_RENDER_OFFSET_X                       (0.0F)
#define ZOMBIE_NORMAL_RENDER_OFFSET_Y                       (0.3F)
#define ZOMBIE_NORMAL_VELOCITY                              (0.2F)
#define ZOMBIE_NORMAL_ATTACK_DELAY                          (1.5F)
#define ZOMBIE_NORMAL_ATTACK_DAMAGE                         (100.0)

#define PROJECTILE_SUN_RENDER_SCALE_X                       (1.3F)
#define PROJECTILE_SUN_RENDER_SCALE_Y                       (1.3F)
#define PROJECTILE_SUN_RENDER_OFFSET_X                      (0.0F)
#define PROJECTILE_SUN_RENDER_OFFSET_Y                      (0.0F)

#define PROJECTILE_PEA_RENDER_SCALE_X                       (1.0F)
#define PROJECTILE_PEA_RENDER_SCALE_Y                       (1.0F)
#define PROJECTILE_PEA_RENDER_OFFSET_X                      (0.0F)
#define PROJECTILE_PEA_RENDER_OFFSET_Y                      (0.0F)

#define PROJECTILE_FIRE_PEA_RENDER_SCALE_X                  (1.6F)
#define PROJECTILE_FIRE_PEA_RENDER_SCALE_Y                  (1.3F)
#define PROJECTILE_FIRE_PEA_RENDER_OFFSET_X                 (0.0F)
#define PROJECTILE_FIRE_PEA_RENDER_OFFSET_Y                 (0.0F)
